name: Print Hello World

on:
  push:
    branches: 
      - main

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Hello World
      - run: echo "Hello World" 
      
